export const
  NAMESPACE_BASE = "basemodels",
  NAMESPACE = "analyseRanking",
  NAMESPACE_ATTACK = "attack",
  NAMESPACE_THREATEVENT = "threatEvent",
  NAMESPACE_CALL_ON_DOMAIN = "callondomain",
  NAMESPACE_CALL_ON_IP = "callonip",
  NAMESPACE_FALL_HOST = "fallhost",
  NAMESPACE_HAVECOMMUNICATEINSIDEIP = "havecommunicateinsideip",
  NAMESPACE_MALDOMAIN = "maldomain",
  NAMESPACE_MALIP = "malip",
  NAMESPACE_SUFFERHOSTCALLONRECORD = "sufferhostcallonrecord",
  NAMESPACE_THREATINFO = "threatinfo",

  VALUE_ATTACK = "statistics",
  VALUE_EVENTREPORT = "eventreport",
  VALUE_THREATEVENT = "threatevent",
  VALUE_CALL_ON_DOMAIN = "callondomain",
  VALUE_CALL_ON_IP = "callonip",
  VALUE_FALL_HOST = "fallhost",
  VALUE_HAVECOMMUNICATEINSIDEIP = "havecommunicateinsideip",
  VALUE_MALDOMAIN = "maldomain",
  VALUE_MALIP = "malip",
  VALUE_SUFFERHOSTCALLONRECORD = "sufferhostcallonrecord",
  VALUE_THREATINFO = "threatinfo",
  VALUE_HIGH = "high",
  VALUE_MIDDLE = "middle",
  VALUE_LOW = "low";

