import {
  LOGIN_URL,

  OVERVIEW_URL,

  ANALYSE_URL,
  ANALYSE_EVENT_URL,
  ANALYSE_ATTACK_CHAIN_URL,
  ANALYSE_FALL_HOST_URL,
  ANALYSE_RANKING_URL,
  ANALYSE_THREAT_DIS_URL,
  ANALYSE_OVERALL_URL,

  EARLY_WARNING_URL,
  EARLY_WARNING_EMAIL_URL,

  REPORT_URL,

  SYS_CONFIG_URL,
  SYS_CONFIG_NETWORK_URL,
  SYS_CONFIG_MONITOR_URL,
  SYS_CONFIG_STRATEGY_URL,

  USER_MANAGER_URL,

  MANAGER_URL,
  MANAGER_DEVICE_URL,
  MANAGER_VM_URL,
  MANAGER_MIRROR_URL,

  SYS_LOG_URL,
  SYS_LOG_LOGIN_URL
} from './path'


export const shouldIdsNodeHide = [
  ANALYSE_ATTACK_CHAIN_URL,
  EARLY_WARNING_URL,
  REPORT_URL,
  SYS_CONFIG_STRATEGY_URL,
  USER_MANAGER_URL,
  MANAGER_VM_URL,
  MANAGER_MIRROR_URL
]

export const shouldIdsStandAloneHide = [
  ANALYSE_ATTACK_CHAIN_URL,
  MANAGER_VM_URL,
  MANAGER_MIRROR_URL
]

export const shouldHoneypotNodeHide = [
  ANALYSE_RANKING_URL,
  ANALYSE_THREAT_DIS_URL,
  EARLY_WARNING_URL,
  REPORT_URL,
  SYS_CONFIG_STRATEGY_URL,
  USER_MANAGER_URL
]

export const adminOnly = [
  SYS_CONFIG_URL,
  USER_MANAGER_URL,
  SYS_LOG_URL
]

export const openRouteList = [
  LOGIN_URL
]